[format]
line-width = 80
indent-width = 4
indent-style = "space"
line-ending = "auto"
persistent-line-breaks = true
exclude = ["data/","output/"]
default-exclude = true
skip = []
table = []
default-table = true